### ISSUE TITLE
Integrate an in-memory cache

### ISSUE THREAD

**Issue by ShreyasPrasad** [loolabs/auth#4]
It's becoming clear that tasks such as password resetting and keeping track of user logins (to prevent brute forcing) will require some in-memory store. This ticket involves researching potential in-memory store caches (i.e `Redis`, `Memcached`) and deciding on one to integrate into the auth microservice. The corresponding spike document for this task can be found [here](https://www.notion.so/Integrating-an-In-Memory-Cache-to-Central-Auth-66147b9da77642abb33f08d2f3378dd4).

This ticket also requires the actual integration of the corresponding store (i.e adding to `Dockerfile`, configuring during app setup).

**Comment by j4orz** [comment]
This is the black-list of tokens essentially re-implementing sessions correct? Just to play devils advocate, are there any pros of just using postgres as our datastore for this cache so we can avoid integrating another component in our system?

Update: Just saw the open-question on #2. What are the pros of adding an extra dependency with Redis/Memcached instead of using postgres as a datastore?
